#!/usr/bin/perl

use strict;
use warnings;

eval { use cPanelUserConfig };

use base qw(Scribe::App);
use CGI::Ex::Die register => 1;
use CGI::Ex::Dump qw(debug);

our $NO_ADD_MSG;
__PACKAGE__->navigate;

sub name_module { 'scribe/scene_board' }

sub url {
    my $self = shift;
    return $self->SUPER::url.'/cgi/scene_board';
}


###-----------------------------------------------------------------###


sub main_hash_swap {
    my $self = shift;

    my $hash = $self->SUPER::main_hash_swap;
    $hash->{'section'} = 'SceneBoard';

    my $scenes = $self->schema->resultset('Scene')->search(
        undef, { order_by => 'weight ASC, name ASC, scene_id ASC' }
    );
    my @rows;
    while (my $scene = $scenes->next) {
        my $hash = {
            scene_id      => $scene->scene_id,
            name          => $scene->name,
            summary       => $scene->summary,
            color         => $scene->label->color,
            document_id   => '',
            document_name => '',
            place_id      => $scene->place_id,
        };
        if(my $doc = $scene->document) {
            $hash->{'document_id'}   = $doc->document_id;
            $hash->{'document_name'} = $doc->name,
        }
        push @rows, $hash;
    }
    $hash->{'scenes'} = \@rows;
    $hash->{'success'} = $self->get_success;

    return $hash;
}


###-----------------------------------------------------------------###


sub scene_order_update_hash_swap { shift->_hash_swap_common('Update Scene Order') }

sub scene_order_update_hash_validation {
    my $self = shift;
    # TODO: Create validation here
    return { }
}

sub scene_order_update_finalize {
    my $self = shift;
    my $form = $self->form;

    if(my $scene_ids = $form->{'scene-id[]'}) {
        my $weight = 0;
        my $resultset = $self->schema->resultset('Scene');
        foreach my $scene_id (@$scene_ids) {
            $resultset->find({ scene_id => $scene_id })->update({weight => $weight});
            $weight += 1;
        }
    }

    return 0;
}


###-----------------------------------------------------------------###


# TODO move this out to cgi/document (or use ScribeDB)
sub document_hash_swap {
    my $self = shift;
    my %form = %{$self->form};

    my $url_theme = $self->url_theme;
    my $hash = $self->_hash_swap_common('Document');

    if(my $id = $form{'document_id'}) {
        my $document = $self->schema->resultset('Document')->find({ document_id => $id });
        $hash->{'document_url_address'} = $document->url_address;
    }

    return $hash;
}

sub document_hash_validation {
    my $self = shift;
    # TODO: Create validation here
    return { }
}


###-----------------------------------------------------------------###


# TODO move this out to cgi/place (or use ScribeDB)
sub place_add_hash_swap {
    my $self = shift;
    my $hash = $self->_hash_swap_common('Add Place');
    $hash->{'places'} = $self->flat_search('Place', undef, { order_by => { -asc => [qw/name/] } });
    return $hash;
}

sub place_add_hash_validation {
    my $self = shift;
    # TODO: Create validation here
    return { }
}

sub place_add_finalize { shift->add_finalize_common('Place') }


###-----------------------------------------------------------------###


# TODO move this out to cgi/character (or use ScribeDB)
sub character_add_hash_swap { shift->_hash_swap_common('Add Character') }

sub character_add_hash_validation {
    my $self = shift;
    # TODO: Create validation here
    return { }
}

sub character_add_finalize { shift->add_finalize_common('Character') }


###-----------------------------------------------------------------###


# TODO move this out to cgi/access_user (or use ScribeDB)
sub access_user_update_hash_swap { shift->_hash_swap_common('Update AccessUser') }

sub access_user_update_hash_validation {
    my $self = shift;
    # TODO: Create validation here
    return { }
}

sub access_user_update_finalize {
    my $self = shift;
    
    $self->schema->resultset('AccessUser')
        ->single({ name     => $self->auth_data->{'user'} })
        ->update({ password => $self->form->{'password'} });

    $self->set_success("AccessUser Updated");

    $self->cgix->location_bounce($self->url);
    return 0;
}


###-----------------------------------------------------------------###


sub more_tools_hash_swap { shift->_hash_swap_common('More Tools') }

sub _hash_swap_common {
    my $self = shift;
    my $headline = shift || die '$headline missing';
    my $url_theme = $self->url_theme;
    return {
        section  => $headline,
        css_crud => "$url_theme/common.css",
    }
}


###-----------------------------------------------------------------###


# TODO move this out to cgi/label (or use ScribeDB)
sub label_add_hash_swap { shift->_hash_swap_common('Add Label') }

sub label_add_hash_validation {
    my $self = shift;
    # TODO: Create validation here
    return { }
}

sub label_add_finalize { shift->add_finalize_common('Label') }

